USE sampleDB02

CREATE TABLE 出荷先 (
    出荷先ID INT IDENTITY(1, 1) CONSTRAINT PK_出荷先ID PRIMARY KEY (出荷先ID),
    出荷先名 NVARCHAR(50) NOT NULL,
    出荷先都道府県 NVARCHAR(10) NOT NULL,
    出荷先住所 NVARCHAR(50) NOT NULL
)

CREATE TABLE 受注 (
    受注ID INT IDENTITY(1001, 1) CONSTRAINT PK_受注ID PRIMARY KEY (受注ID),
    出荷先ID INT NOT NULL CONSTRAINT FK_出荷先ID FOREIGN KEY (出荷先ID) REFERENCES 出荷先(出荷先ID),
    受注日 DATE NOT NULL
)

CREATE TABLE 商品 (
    商品ID INT IDENTITY(1, 1) CONSTRAINT PK_商品ID PRIMARY KEY (商品ID),
    商品名 NVARCHAR(30) NOT NULL,
    区分 NVARCHAR(10)
)

CREATE TABLE 受注明細 (
    受注ID INT NOT NULL CONSTRAINT FK_受注ID FOREIGN KEY (受注ID) REFERENCES 受注(受注ID),
    商品ID INT NOT NULL CONSTRAINT FK_商品ID FOREIGN KEY (商品ID) REFERENCES 商品(商品ID),
    単価 MONEY NOT NULL,
    数量 INT NOT NULL
)
   
--データをinsert後

